# Generated by Django 5.0.7 on 2024-07-15 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_quote_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
